### ISSUE TITLE
Archives page

### ISSUE THREAD

**Issue by luigi** [sunlightlabs/datajam#10]
When events have concluded, they should automatically be added to an archive page at `/archives`. The page will use the site template and list and link to past events (via their slug) in reverse chronological order.

This will require a nightly task to be set up and run.

**Comment by foca** [comment]
This should work, though for already existing systems you should probably re-generate all pages. I added a `Cacher.reset!` convenience method that will do that.

The only quirk right now is that whenever you browse to an event's page (`/{{ slug }}`) it will render the "ON AIR" topbar, whether the event is on air or not. We should probably have a global indicator to see if there's an event currently airing or not, but that's surely something for a new issue :)

**Comment by drinks** [comment]
Getting the following error when saving any event template:

```
2012-02-16T20:14:05+00:00 app[web.1]: Completed 500 Internal Server Error in 108ms
2012-02-16T20:14:05+00:00 app[web.1]: 
2012-02-16T20:14:05+00:00 app[web.1]: V8::JSError (Parse error on line 9:
    {{ content_area: Video pp[web.1]: ...allModule">
2012-02-16T20:14:05+00:00 app[web.1]: ----------------------^
2012-02-16T20:14:05+00:00 app[web.1]: Expecting 'ID'):
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/template.rb:22:in `render_with'
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/event.rb:59:in `render'
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/cacher.rb:21:in `block in cache_events'
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/cacher.rb:15:in `each'
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/cacher.rb:15:in `cache_events'
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/event.rb:28:in `block in <class:Event>'
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/event_template.rb:6:in `block (2 levels) in <class:EventTemplate>'
2012-02-16T20:14:05+00:00 app[web.1]:   app/models/event_template.rb:6:in `block in <class:EventTemplate>'
2012-02-16T20:14:05+00:00 app[web.1]:   app/controllers/admin/templates/events_controller.rb:25:in `update'
2012-02-16T20:14:05+00:00 app[web.1]:   app/middlewares/redis_cache.rb:25:in `call'
```

Looks similar to the issue referenced in the comments in e93cef4

**Comment by drinks** [comment]
This looks great. My only comment is that rather than raising a 404, the /archives/ path should display a page with the message 'There are no archived events.' It also would be nice to have a more descriptive error message when an event slug collides with an existing page. Currently I get 'There was an error saving the event.'
